/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas.presentacion;
import ventas.presentacion.Mesa.jpListarMesa;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JPanel;
import ventas.modelo.DevClass;

/**
 *
 * @author Test
 */
public class frmPrincipal extends javax.swing.JFrame {
    public JPanel nPanel;
    public int widthvar, heightvar;
    
    public frmPrincipal() {
        initComponents();
        getContentPane().setLayout(null);
        Login frmL = new Login();
        
        setExtendedState(MAXIMIZED_BOTH);
        widthvar = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        heightvar = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
  
        pTop.setBounds(0,0,widthvar, 59);
        Validar(frmL.id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTop = new javax.swing.JPanel();
        pMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pPedido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pProducts = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pMesas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pReporte = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pUsuario = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 252, 230));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pTop.setBackground(new java.awt.Color(0, 148, 90));

        javax.swing.GroupLayout pTopLayout = new javax.swing.GroupLayout(pTop);
        pTop.setLayout(pTopLayout);
        pTopLayout.setHorizontalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1214, Short.MAX_VALUE)
        );
        pTopLayout.setVerticalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        getContentPane().add(pTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pMenu.setBackground(new java.awt.Color(0, 152, 205));
        pMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMenuMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/carta2.png"))); // NOI18N

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(pMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, -1, -1));

        pPedido.setBackground(new java.awt.Color(0, 152, 205));
        pPedido.setPreferredSize(new java.awt.Dimension(255, 120));
        pPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPedidoMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pedido");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/list.png"))); // NOI18N

        javax.swing.GroupLayout pPedidoLayout = new javax.swing.GroupLayout(pPedido);
        pPedido.setLayout(pPedidoLayout);
        pPedidoLayout.setHorizontalGroup(
            pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPedidoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(63, 63, 63))
        );
        pPedidoLayout.setVerticalGroup(
            pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPedidoLayout.createSequentialGroup()
                .addGroup(pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPedidoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(pPedidoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );

        jLabel4.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 179, -1, -1));

        pProducts.setBackground(new java.awt.Color(0, 152, 205));
        pProducts.setPreferredSize(new java.awt.Dimension(255, 120));
        pProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pProductsMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Productos");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pedido2.png"))); // NOI18N

        javax.swing.GroupLayout pProductsLayout = new javax.swing.GroupLayout(pProducts);
        pProducts.setLayout(pProductsLayout);
        pProductsLayout.setHorizontalGroup(
            pProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pProductsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pProductsLayout.setVerticalGroup(
            pProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProductsLayout.createSequentialGroup()
                .addGroup(pProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pProductsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14))
                    .addGroup(pProductsLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 659, -1, -1));

        pMesas.setBackground(new java.awt.Color(0, 152, 205));
        pMesas.setPreferredSize(new java.awt.Dimension(255, 120));
        pMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMesasMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mesas");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/table.png"))); // NOI18N

        javax.swing.GroupLayout pMesasLayout = new javax.swing.GroupLayout(pMesas);
        pMesas.setLayout(pMesasLayout);
        pMesasLayout.setHorizontalGroup(
            pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMesasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pMesasLayout.setVerticalGroup(
            pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesasLayout.createSequentialGroup()
                .addGroup(pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12))
                    .addGroup(pMesasLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel11)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(pMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 539, -1, -1));

        pReporte.setBackground(new java.awt.Color(0, 152, 205));
        pReporte.setPreferredSize(new java.awt.Dimension(255, 120));
        pReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pReporteMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reporte");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/rpt.png"))); // NOI18N

        javax.swing.GroupLayout pReporteLayout = new javax.swing.GroupLayout(pReporte);
        pReporte.setLayout(pReporteLayout);
        pReporteLayout.setHorizontalGroup(
            pReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pReporteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pReporteLayout.setVerticalGroup(
            pReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReporteLayout.createSequentialGroup()
                .addGroup(pReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pReporteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8))
                    .addGroup(pReporteLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(pReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 419, -1, -1));

        pUsuario.setBackground(new java.awt.Color(0, 152, 205));
        pUsuario.setPreferredSize(new java.awt.Dimension(255, 120));
        pUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pUsuarioMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuarios");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/users.png"))); // NOI18N

        javax.swing.GroupLayout pUsuarioLayout = new javax.swing.GroupLayout(pUsuario);
        pUsuario.setLayout(pUsuarioLayout);
        pUsuarioLayout.setHorizontalGroup(
            pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsuarioLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addGap(41, 41, 41))
        );
        pUsuarioLayout.setVerticalGroup(
            pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsuarioLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(45, 45, 45))
        );

        getContentPane().add(pUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 299, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMenuMouseClicked
        pPedido.setBackground(new java.awt.Color(0,152,205));
        pMenu.setBackground(new java.awt.Color(255,51,51));
        pUsuario.setBackground(new java.awt.Color(0,152,205));
        pReporte.setBackground(new java.awt.Color(0,152,205));
        pMesas.setBackground(new java.awt.Color(0,152,205));
        pProducts.setBackground(new java.awt.Color(0,152,205));
        try {
        if(nPanel != null){
        getContentPane().remove(nPanel);
        getContentPane().repaint();
        }
        nPanel = new jpMenu();
        nPanel.setBounds(255, 59, widthvar-255, heightvar-59);
        
        getContentPane().add(nPanel);
        this.validate();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_pMenuMouseClicked

    private void pPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPedidoMouseClicked
        pPedido.setBackground(new java.awt.Color(255,51,51));
        pMenu.setBackground(new java.awt.Color(0,152,205));
        pUsuario.setBackground(new java.awt.Color(0,152,205));
        pReporte.setBackground(new java.awt.Color(0,152,205));
        pMesas.setBackground(new java.awt.Color(0,152,205));
        pProducts.setBackground(new java.awt.Color(0,152,205));
        try {
        if(nPanel != null){
        getContentPane().remove(nPanel);
        getContentPane().repaint();}
         nPanel = new jpPedido();
        nPanel.setBounds(255, 59, widthvar-255, heightvar-59);
        
        getContentPane().add(nPanel);
        this.validate();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pPedidoMouseClicked

    private void pReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pReporteMouseClicked
       pReporte.setBackground(new java.awt.Color(255,51,51));
       pPedido.setBackground(new java.awt.Color(0,152,205));
       pMenu.setBackground(new java.awt.Color(0,152,205));
       pUsuario.setBackground(new java.awt.Color(0,152,205));
       pMesas.setBackground(new java.awt.Color(0,152,205));
       pProducts.setBackground(new java.awt.Color(0,152,205));
    }//GEN-LAST:event_pReporteMouseClicked

    private void pUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pUsuarioMouseClicked
       pUsuario.setBackground(new java.awt.Color(255,51,51));
       pPedido.setBackground(new java.awt.Color(0,152,205));
       pMenu.setBackground(new java.awt.Color(0,152,205));
       pReporte.setBackground(new java.awt.Color(0,152,205));
       pMesas.setBackground(new java.awt.Color(0,152,205));
       pProducts.setBackground(new java.awt.Color(0,152,205));
    }//GEN-LAST:event_pUsuarioMouseClicked

    private void pMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMesasMouseClicked
       pUsuario.setBackground(new java.awt.Color(0,152,205));
       pPedido.setBackground(new java.awt.Color(0,152,205));
       pMenu.setBackground(new java.awt.Color(0,152,205));
       pReporte.setBackground(new java.awt.Color(0,152,205));
       pMesas.setBackground(new java.awt.Color(255,51,51));
       pProducts.setBackground(new java.awt.Color(0,152,205));
       try {
            if(nPanel != null){
                getContentPane().remove(nPanel);
                getContentPane().repaint();
            }
            nPanel = new jpListarMesa();
            nPanel.setBounds(255, 59, widthvar-255, heightvar-59);
        
            getContentPane().add(nPanel);
            this.validate();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_pMesasMouseClicked

    private void pProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pProductsMouseClicked
       pUsuario.setBackground(new java.awt.Color(0,152,205));
       pPedido.setBackground(new java.awt.Color(0,152,205));
       pMenu.setBackground(new java.awt.Color(0,152,205));
       pReporte.setBackground(new java.awt.Color(0,152,205));
       pMesas.setBackground(new java.awt.Color(0,152,205));
       pProducts.setBackground(new java.awt.Color(255,51,51));
    }//GEN-LAST:event_pProductsMouseClicked
    public void Validar(int id){
        int vis = 6;
        int size = 0;
        
        if(id == 1){
            vis = 6;
            size = (heightvar - pTop.getHeight())/vis;    
            pMesas.setVisible(true);
            pProducts.setVisible(true);
            pReporte.setVisible(true);
            pUsuario.setVisible(true);
            pMenu.setLayout(null);
            pPedido.setLayout(null);
            pUsuario.setLayout(null);
            pReporte.setLayout(null);
            pMesas.setLayout(null);
            pProducts.setLayout(null);

            pMenu.setBounds(0, 59, 250,size);
            jLabel1.setBounds(110, size/2 - 20, 57, 26);
            jLabel2.setBounds(36, size/2 - 50, 82, 77);
            //System.out.println(pMenu.getLocation().toString());

            pPedido.setBounds(0, 59 + size, 250, size);
            jLabel3.setBounds(110, size/2 - 20, 73, 26);
            jLabel4.setBounds(36, size/2 - 30, 48, 48);
            //System.out.println(pPedido.getLocation().toString());

            pUsuario.setBounds(0, 59 + size*2,250,size);
            jLabel9.setBounds(110, size/2 - 20, 95, 26);
            jLabel10.setBounds(36, size/2 - 30, 48, 48);
           // System.out.println(pUsuario.getLocation().toString());

            pReporte.setBounds(0,59 + size*3,250,size);
            jLabel7.setBounds(110, size/2 - 20, 85, 26);
            jLabel8.setBounds(36, size/2 - 40, 64, 64);
            //System.out.println(pReporte.getLocation().toString());

            pMesas.setBounds(0, 59 + size*4, 250, size);
            jLabel11.setBounds(110, size/2 - 20,68 ,26);
            jLabel12.setBounds(36, size/2 - 40,64 ,64);
           // System.out.println(pMesas.getLocation().toString());

            pProducts.setBounds(0, 59 + size*5, 250, size);
            jLabel13.setBounds(110, size/2 - 20,109 ,26);
            jLabel14.setBounds(36, size/2 -40,64 ,64);
            //System.out.println(pProducts.getLocation().toString());

        }else if(id==2){
            vis = 5;
            size = (heightvar - pTop.getHeight())/vis;    
            pMesas.setVisible(true);
            pProducts.setVisible(true);
            //pReporte.setVisible(true);
            pUsuario.setVisible(true);
            pMenu.setLayout(null);
            pPedido.setLayout(null);
            pUsuario.setLayout(null);
            //pReporte.setLayout(null);
            pMesas.setLayout(null);
            pProducts.setLayout(null);

            pMenu.setBounds(0, 59, 250,size);
            jLabel1.setBounds(110, size/2 - 20, 57, 26);
            jLabel2.setBounds(36, size/2 - 50, 82, 77);
            //System.out.println(pMenu.getLocation().toString());

            pPedido.setBounds(0, 59 + size, 250, size);
            jLabel3.setBounds(110, size/2 - 20, 73, 26);
            jLabel4.setBounds(36, size/2 - 30, 48, 48);
            //System.out.println(pPedido.getLocation().toString());

            pUsuario.setBounds(0, 59 + size*2,250,size);
            jLabel9.setBounds(110, size/2 - 20, 95, 26);
            jLabel10.setBounds(36, size/2 - 30, 48, 48);
           // System.out.println(pUsuario.getLocation().toString());

            pMesas.setBounds(0, 59 + size*3, 250, size);
            jLabel11.setBounds(110, size/2 - 20,68 ,26);
            jLabel12.setBounds(36, size/2 - 40,64 ,64);
           // System.out.println(pMesas.getLocation().toString());

            pProducts.setBounds(0, 59 + size*4, 250, size);
            jLabel13.setBounds(110, size/2 - 20,109 ,26);
            jLabel14.setBounds(36, size/2 -40,64 ,64);
            //System.out.println(pProducts.getLocation().toString());

        }else{
            vis = 2;
            size = (heightvar - pTop.getHeight())/vis;
        pMesas.setVisible(false);
        pProducts.setVisible(false);
        pReporte.setVisible(false);
        pUsuario.setVisible(false);
        pMenu.setLayout(null);
        pPedido.setLayout(null);
         pMenu.setBounds(0, 59, 250,size);
        jLabel1.setBounds(110, size/2 - 20, 57, 26);
        jLabel2.setBounds(36, size/2 - 50, 82, 77);
       // System.out.println(pMenu.getLocation().toString());
        
        pPedido.setBounds(0, 59 + size, 250, size);
        jLabel3.setBounds(110, size/2 - 20, 73, 26);
        jLabel4.setBounds(36, size/2 - 30, 48, 48);
        //System.out.println(pPedido.getLocation().toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pMesas;
    private javax.swing.JPanel pPedido;
    private javax.swing.JPanel pProducts;
    private javax.swing.JPanel pReporte;
    private javax.swing.JPanel pTop;
    private javax.swing.JPanel pUsuario;
    // End of variables declaration//GEN-END:variables
}
