
package ventas.presentacion;
import ventas.presentacion.Mesa.jpListarMesa;
import ventas.presentacion.Usuario.Usuarios_new;
import ventas.presentacion.Trabajador.Trabajador_new;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JPanel;
import ventas.modelo.Login_User;
import ventas.persistencia.util.BDUtil;
import ventas.presentacion.Area.AreaL;
import ventas.presentacion.Cargo.CargoL;
import ventas.presentacion.Empresa.jpListarEmpresa;
import ventas.presentacion.Empresa.jpNuevaEmpresa;
import ventas.presentacion.Local.jpListaLocal;
import ventas.presentacion.Local.jpNuevoLocal;
import ventas.presentacion.Trabajador.Mant_Trabajador;
import ventas.presentacion.Usuario.Mant_Usuarios;

public class frmPrincipal extends javax.swing.JFrame {
    public static JPanel nPanel;
    public static int widthvar, heightvar;
    public static Container c ;
    Login_User usuario =new Login_User();
    Login frmL;
    public int pnelActive = 0;
    public frmPrincipal() {
        initComponents();
        c = getContentPane();
        getContentPane().setLayout(null);
        frmL = new Login();
        setExtendedState(MAXIMIZED_BOTH);
        widthvar = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        heightvar = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        pTop.setLayout(null);
        pTop.setBounds(0,0,widthvar, 59);
        btnHome.setBounds(widthvar-75, 0, 55, 57);
            pMesas.setVisible(false);
            pComprobante.setVisible(false);
            pUsuario.setVisible(false);
            pTrabajador.setVisible(false);
            pArea.setVisible(false);
            pCliente.setVisible(false);
            pCargo.setVisible(false);
            pCategoria.setVisible(false);
            pEmpresa.setVisible(false);
            pLocal.setVisible(false);
            pPlato.setVisible(false);
            pPlatoLocal.setVisible(false);
            pPiso.setVisible(false);            
            mpMante.setVisible(false);
            mpReporte.setVisible(false);
            mpPedido.setVisible(false);
            mpMante.setVisible(false);
        //jpContenedor.setBounds(255, 59, widthvar - 255, heightvar-59);
        jpContenedor.setVisible(false);
        jLabel15.setLocation(widthvar/2, 15);
        //jpContenedor.setBounds(255, 59, widthvar-255, heightvar-59);
       // Validar(frmL.id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTop = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        pTrabajador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mpPedido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mpMante = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pMesas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mpReporte = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pUsuario = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpContenedor = new javax.swing.JPanel();
        pComprobante = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pArea = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pCargo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        pPiso = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pEmpresa = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pCliente = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pLocal = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pPlato = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        pCategoria = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pPlatoLocal = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 252, 230));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pTop.setBackground(new java.awt.Color(68, 134, 187));

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sistema de Gestión");

        btnHome.setBackground(new java.awt.Color(68, 134, 187));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Home-icon.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pTopLayout = new javax.swing.GroupLayout(pTop);
        pTop.setLayout(pTopLayout);
        pTopLayout.setHorizontalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(485, 485, 485)
                .addComponent(jLabel15)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        pTopLayout.setVerticalGroup(
            pTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pTopLayout.createSequentialGroup()
                .addComponent(btnHome)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        getContentPane().add(pTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        pTrabajador.setBackground(new java.awt.Color(24, 168, 255));
        pTrabajador.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pTrabajador.setPreferredSize(new java.awt.Dimension(255, 120));
        pTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTrabajadorMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trabajadores");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/worker.png"))); // NOI18N

        javax.swing.GroupLayout pTrabajadorLayout = new javax.swing.GroupLayout(pTrabajador);
        pTrabajador.setLayout(pTrabajadorLayout);
        pTrabajadorLayout.setHorizontalGroup(
            pTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTrabajadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(88, 88, 88))
        );
        pTrabajadorLayout.setVerticalGroup(
            pTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTrabajadorLayout.createSequentialGroup()
                .addGroup(pTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTrabajadorLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTrabajadorLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(pTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 255, 120));

        mpPedido.setBackground(new java.awt.Color(24, 168, 255));
        mpPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        mpPedido.setPreferredSize(new java.awt.Dimension(255, 120));
        mpPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpPedidoMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pedido");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/list.png"))); // NOI18N

        javax.swing.GroupLayout mpPedidoLayout = new javax.swing.GroupLayout(mpPedido);
        mpPedido.setLayout(mpPedidoLayout);
        mpPedidoLayout.setHorizontalGroup(
            mpPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpPedidoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(63, 63, 63))
        );
        mpPedidoLayout.setVerticalGroup(
            mpPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpPedidoLayout.createSequentialGroup()
                .addGroup(mpPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mpPedidoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(mpPedidoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );

        jLabel4.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(mpPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        mpMante.setBackground(new java.awt.Color(24, 168, 255));
        mpMante.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        mpMante.setPreferredSize(new java.awt.Dimension(255, 120));
        mpMante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpManteMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mantenimiento");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/protest.png"))); // NOI18N

        javax.swing.GroupLayout mpManteLayout = new javax.swing.GroupLayout(mpMante);
        mpMante.setLayout(mpManteLayout);
        mpManteLayout.setHorizontalGroup(
            mpManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpManteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        mpManteLayout.setVerticalGroup(
            mpManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mpManteLayout.createSequentialGroup()
                .addGroup(mpManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mpManteLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel13))
                    .addGroup(mpManteLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel14)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(mpMante, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 60, 260, -1));

        pMesas.setBackground(new java.awt.Color(24, 168, 255));
        pMesas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pMesas.setPreferredSize(new java.awt.Dimension(255, 120));
        pMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMesasMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mesas");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/t2.png"))); // NOI18N

        javax.swing.GroupLayout pMesasLayout = new javax.swing.GroupLayout(pMesas);
        pMesas.setLayout(pMesasLayout);
        pMesasLayout.setHorizontalGroup(
            pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMesasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pMesasLayout.setVerticalGroup(
            pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesasLayout.createSequentialGroup()
                .addGroup(pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesasLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel11))
                    .addGroup(pMesasLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(pMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        mpReporte.setBackground(new java.awt.Color(24, 168, 255));
        mpReporte.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        mpReporte.setPreferredSize(new java.awt.Dimension(255, 120));
        mpReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpReporteMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reporte");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/rpt.png"))); // NOI18N

        javax.swing.GroupLayout mpReporteLayout = new javax.swing.GroupLayout(mpReporte);
        mpReporte.setLayout(mpReporteLayout);
        mpReporteLayout.setHorizontalGroup(
            mpReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpReporteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        mpReporteLayout.setVerticalGroup(
            mpReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mpReporteLayout.createSequentialGroup()
                .addGroup(mpReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mpReporteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8))
                    .addGroup(mpReporteLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(mpReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        pUsuario.setBackground(new java.awt.Color(24, 168, 255));
        pUsuario.setPreferredSize(new java.awt.Dimension(255, 120));
        pUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pUsuarioMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuarios");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/users.png"))); // NOI18N

        javax.swing.GroupLayout pUsuarioLayout = new javax.swing.GroupLayout(pUsuario);
        pUsuario.setLayout(pUsuarioLayout);
        pUsuarioLayout.setHorizontalGroup(
            pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(41, 41, 41))
        );
        pUsuarioLayout.setVerticalGroup(
            pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsuarioLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24))))
        );

        getContentPane().add(pUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 10, 10));

        pComprobante.setBackground(new java.awt.Color(24, 168, 255));
        pComprobante.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pComprobante.setPreferredSize(new java.awt.Dimension(255, 120));
        pComprobante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pComprobanteMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Comprobante");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/stairs.png"))); // NOI18N

        javax.swing.GroupLayout pComprobanteLayout = new javax.swing.GroupLayout(pComprobante);
        pComprobante.setLayout(pComprobanteLayout);
        pComprobanteLayout.setHorizontalGroup(
            pComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pComprobanteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        pComprobanteLayout.setVerticalGroup(
            pComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pComprobanteLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(45, 45, 45))
            .addGroup(pComprobanteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        pArea.setBackground(new java.awt.Color(24, 168, 255));
        pArea.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pArea.setPreferredSize(new java.awt.Dimension(255, 120));
        pArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAreaMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Área");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/area.png"))); // NOI18N

        javax.swing.GroupLayout pAreaLayout = new javax.swing.GroupLayout(pArea);
        pArea.setLayout(pAreaLayout);
        pAreaLayout.setHorizontalGroup(
            pAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAreaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        pAreaLayout.setVerticalGroup(
            pAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAreaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel19)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(46, 46, 46))
        );

        getContentPane().add(pArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));

        pCargo.setBackground(new java.awt.Color(24, 168, 255));
        pCargo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pCargo.setPreferredSize(new java.awt.Dimension(255, 120));
        pCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCargoMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cargo");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/collaboration.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Cargo");

        javax.swing.GroupLayout pCargoLayout = new javax.swing.GroupLayout(pCargo);
        pCargo.setLayout(pCargoLayout);
        pCargoLayout.setHorizontalGroup(
            pCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCargoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addGap(40, 40, 40)
                .addComponent(jLabel36)
                .addGap(179, 179, 179)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCargoLayout.setVerticalGroup(
            pCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCargoLayout.createSequentialGroup()
                .addGroup(pCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCargoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel17))
                    .addGroup(pCargoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel36))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(pCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        pPiso.setBackground(new java.awt.Color(24, 168, 255));
        pPiso.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pPiso.setPreferredSize(new java.awt.Dimension(255, 120));
        pPiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPisoMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Piso");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/stairs.png"))); // NOI18N

        javax.swing.GroupLayout pPisoLayout = new javax.swing.GroupLayout(pPiso);
        pPiso.setLayout(pPisoLayout);
        pPisoLayout.setHorizontalGroup(
            pPisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPisoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(61, 61, 61)
                .addComponent(jLabel22)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pPisoLayout.setVerticalGroup(
            pPisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPisoLayout.createSequentialGroup()
                .addGroup(pPisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPisoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel22))
                    .addGroup(pPisoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel23)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(pPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        pEmpresa.setBackground(new java.awt.Color(24, 168, 255));
        pEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pEmpresa.setPreferredSize(new java.awt.Dimension(255, 120));
        pEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pEmpresaMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Empresa");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/stairs.png"))); // NOI18N

        javax.swing.GroupLayout pEmpresaLayout = new javax.swing.GroupLayout(pEmpresa);
        pEmpresa.setLayout(pEmpresaLayout);
        pEmpresaLayout.setHorizontalGroup(
            pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(61, 61, 61)
                .addComponent(jLabel24)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pEmpresaLayout.setVerticalGroup(
            pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmpresaLayout.createSequentialGroup()
                .addGroup(pEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEmpresaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel24))
                    .addGroup(pEmpresaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel25)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(pEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        pCliente.setBackground(new java.awt.Color(24, 168, 255));
        pCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pCliente.setPreferredSize(new java.awt.Dimension(255, 120));
        pCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pClienteMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Cliente");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/stairs.png"))); // NOI18N

        javax.swing.GroupLayout pClienteLayout = new javax.swing.GroupLayout(pCliente);
        pCliente.setLayout(pClienteLayout);
        pClienteLayout.setHorizontalGroup(
            pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClienteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel27)
                .addGap(48, 48, 48)
                .addComponent(jLabel26)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pClienteLayout.setVerticalGroup(
            pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClienteLayout.createSequentialGroup()
                .addGroup(pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pClienteLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel26))
                    .addGroup(pClienteLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel27)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(pCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        pLocal.setBackground(new java.awt.Color(24, 168, 255));
        pLocal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pLocal.setPreferredSize(new java.awt.Dimension(255, 120));
        pLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLocalMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Local");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/stairs.png"))); // NOI18N

        javax.swing.GroupLayout pLocalLayout = new javax.swing.GroupLayout(pLocal);
        pLocal.setLayout(pLocalLayout);
        pLocalLayout.setHorizontalGroup(
            pLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(61, 61, 61)
                .addComponent(jLabel28)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pLocalLayout.setVerticalGroup(
            pLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLocalLayout.createSequentialGroup()
                .addGroup(pLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLocalLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel28))
                    .addGroup(pLocalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel29)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(pLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        pPlato.setBackground(new java.awt.Color(24, 168, 255));
        pPlato.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pPlato.setPreferredSize(new java.awt.Dimension(255, 120));
        pPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPlatoMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Plato");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/stairs.png"))); // NOI18N

        javax.swing.GroupLayout pPlatoLayout = new javax.swing.GroupLayout(pPlato);
        pPlato.setLayout(pPlatoLayout);
        pPlatoLayout.setHorizontalGroup(
            pPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPlatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(61, 61, 61)
                .addComponent(jLabel30)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pPlatoLayout.setVerticalGroup(
            pPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPlatoLayout.createSequentialGroup()
                .addGroup(pPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPlatoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel30))
                    .addGroup(pPlatoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel31)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(pPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        pCategoria.setBackground(new java.awt.Color(24, 168, 255));
        pCategoria.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pCategoria.setPreferredSize(new java.awt.Dimension(255, 120));
        pCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCategoriaMouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Categoria");

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/stairs.png"))); // NOI18N

        javax.swing.GroupLayout pCategoriaLayout = new javax.swing.GroupLayout(pCategoria);
        pCategoria.setLayout(pCategoriaLayout);
        pCategoriaLayout.setHorizontalGroup(
            pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(61, 61, 61)
                .addComponent(jLabel32)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pCategoriaLayout.setVerticalGroup(
            pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCategoriaLayout.createSequentialGroup()
                .addGroup(pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCategoriaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel32))
                    .addGroup(pCategoriaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel33)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(pCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        pPlatoLocal.setBackground(new java.awt.Color(24, 168, 255));
        pPlatoLocal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(61, 217, 237)));
        pPlatoLocal.setPreferredSize(new java.awt.Dimension(255, 120));
        pPlatoLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPlatoLocalMouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Plato Local");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/stairs.png"))); // NOI18N

        javax.swing.GroupLayout pPlatoLocalLayout = new javax.swing.GroupLayout(pPlatoLocal);
        pPlatoLocal.setLayout(pPlatoLocalLayout);
        pPlatoLocalLayout.setHorizontalGroup(
            pPlatoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPlatoLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(30, 30, 30))
        );
        pPlatoLocalLayout.setVerticalGroup(
            pPlatoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPlatoLocalLayout.createSequentialGroup()
                .addGroup(pPlatoLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPlatoLocalLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel34))
                    .addGroup(pPlatoLocalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel35)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(pPlatoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void pTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {                                         
        //mpPedido.setBackground(new java.awt.Color(24,168,255));
        pTrabajador.setBackground(new java.awt.Color(255,51,51));
        pUsuario.setBackground(new java.awt.Color(24,168,255));
        //mpReporte.setBackground(new java.awt.Color(24,168,255));
        pMesas.setBackground(new java.awt.Color(24,168,255));
        //mpMante.setBackground(new java.awt.Color(24,168,255));
        pArea.setBackground(new java.awt.Color(24,168,255));
        pCargo.setBackground(new java.awt.Color(24,168,255));
        pComprobante.setBackground(new java.awt.Color(24,168,255));
        try {
            if(nPanel != null){
                getContentPane().remove(nPanel);
                getContentPane().repaint();
            }
            nPanel = new Mant_Trabajador();
            nPanel.setBounds(255,59, widthvar-255, heightvar-59);
        
            getContentPane().add(nPanel);
            this.validate();
            } catch (Exception e) {
        }}

    private void mpPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpPedidoMouseClicked
        mpPedido.setBackground(new java.awt.Color(255,51,51));
        //pTrabajador.setBackground(new java.awt.Color(24,168,255));
        //pUsuario.setBackground(new java.awt.Color(24,168,255));
        mpReporte.setBackground(new java.awt.Color(24,168,255));
        //pMesas.setBackground(new java.awt.Color(24,168,255));
        mpMante.setBackground(new java.awt.Color(24,168,255));
        //pArea.setBackground(new java.awt.Color(24,168,255));
        //pCargo.setBackground(new java.awt.Color(24,168,255));
        pnelActive = 2;
    }//GEN-LAST:event_mpPedidoMouseClicked
    public static void Comp(JPanel j){
        try {
            nPanel.setVisible(false);
        if(nPanel != null){
            
        c.remove(nPanel);
        
        c.repaint();
        }
        nPanel = j;
        nPanel.setBounds(255, 59, widthvar-255, heightvar-59);
        nPanel.setVisible(true);
        c.add(nPanel);
        c.validate();
        } catch (Exception e) {
        }
    }
    private void mpReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpReporteMouseClicked
       mpReporte.setBackground(new java.awt.Color(255,51,51));
       mpPedido.setBackground(new java.awt.Color(24,168,255));
       //pTrabajador.setBackground(new java.awt.Color(24,168,255));
       //pUsuario.setBackground(new java.awt.Color(24,168,255));
       //pMesas.setBackground(new java.awt.Color(24,168,255));
       mpMante.setBackground(new java.awt.Color(24,168,255));
       //pArea.setBackground(new java.awt.Color(24,168,255));
       //pCargo.setBackground(new java.awt.Color(24,168,255));
       pnelActive = 3;
    }//GEN-LAST:event_mpReporteMouseClicked

    private void pUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pUsuarioMouseClicked
       pUsuario.setBackground(new java.awt.Color(255,51,51));
       //mpPedido.setBackground(new java.awt.Color(24,168,255));
       pTrabajador.setBackground(new java.awt.Color(24,168,255));
       //mpReporte.setBackground(new java.awt.Color(24,168,255));
       pMesas.setBackground(new java.awt.Color(24,168,255));
       //mpMante.setBackground(new java.awt.Color(24,168,255));
       pArea.setBackground(new java.awt.Color(24,168,255));
       pCargo.setBackground(new java.awt.Color(24,168,255));
       pComprobante.setBackground(new java.awt.Color(24,168,255));
        try {
            if(nPanel != null){
                getContentPane().remove(nPanel);
                getContentPane().repaint();
            }
            nPanel = new Mant_Usuarios();
            nPanel.setBounds(255,59, widthvar-255, heightvar-59);
        
            getContentPane().add(nPanel);
            this.validate();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pUsuarioMouseClicked

    private void pMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMesasMouseClicked

       pUsuario.setBackground(new java.awt.Color(24,168,255));
       //mpPedido.setBackground(new java.awt.Color(24,168,255));
       pTrabajador.setBackground(new java.awt.Color(24,168,255));
       //mpReporte.setBackground(new java.awt.Color(24,168,255));
       pArea.setBackground(new java.awt.Color(24,168,255));
       pCargo.setBackground(new java.awt.Color(24,168,255));
       pMesas.setBackground(new java.awt.Color(255,51,51));
       pComprobante.setBackground(new java.awt.Color(24,168,255));
       //mpMante.setBackground(new java.awt.Color(24,168,255));
       try {
            if(nPanel != null){
                getContentPane().remove(nPanel);
                getContentPane().repaint();
            }
            nPanel = new jpListarMesa();
            nPanel.setBounds(255,59, widthvar-255, heightvar-59);
        
            getContentPane().add(nPanel);
            this.validate();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_pMesasMouseClicked

    private void mpManteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpManteMouseClicked
            pMesas.setBackground(new java.awt.Color(24,168,255));
            pUsuario.setBackground(new java.awt.Color(24,168,255));
            pTrabajador.setBackground(new java.awt.Color(24,168,255));
            pCargo.setBackground(new java.awt.Color(24,168,255));
            pArea.setBackground(new java.awt.Color(24,168,255));
            pComprobante.setBackground(new java.awt.Color(24,168,255));
        //pUsuario.setBackground(new java.awt.Color(24,168,255));
       mpPedido.setBackground(new java.awt.Color(24,168,255));
       //pTrabajador.setBackground(new java.awt.Color(24,168,255));
       mpReporte.setBackground(new java.awt.Color(24,168,255));
       //pMesas.setBackground(new java.awt.Color(24,168,255));
       mpMante.setBackground(new java.awt.Color(255,51,51));
       //pArea.setBackground(new java.awt.Color(24,168,255));
       //pCargo.setBackground(new java.awt.Color(24,168,255));}
       mpMante.setVisible(false);
       mpPedido.setVisible(false);
       mpReporte.setVisible(false);
       ValidarSub(usuario.getNid_perfil());
       pnelActive = 1;
    }//GEN-LAST:event_mpManteMouseClicked

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
       
    }//GEN-LAST:event_formWindowStateChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        //jpContenedor.validate();// TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void pCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCargoMouseClicked
       pUsuario.setBackground(new java.awt.Color(24,168,255));
       //mpPedido.setBackground(new java.awt.Color(24,168,255));
       pTrabajador.setBackground(new java.awt.Color(24,168,255));
       //mpReporte.setBackground(new java.awt.Color(24,168,255));
       pMesas.setBackground(new java.awt.Color(24,168,255));
       //mpMante.setBackground(new java.awt.Color(24,168,255));
       pArea.setBackground(new java.awt.Color(24,168,255));
       pCargo.setBackground(new java.awt.Color(255,51,51));
       pComprobante.setBackground(new java.awt.Color(24,168,255));
       try {
            if(nPanel != null){
                getContentPane().remove(nPanel);
                getContentPane().repaint();
            }
            nPanel = new CargoL();
            nPanel.setBounds(255,59, widthvar-255, heightvar-59);
        
            getContentPane().add(nPanel);
            this.validate();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pCargoMouseClicked

    private void pAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAreaMouseClicked
       pUsuario.setBackground(new java.awt.Color(24,168,255));
       //mpPedido.setBackground(new java.awt.Color(24,168,255));
       pTrabajador.setBackground(new java.awt.Color(24,168,255));
       //mpReporte.setBackground(new java.awt.Color(24,168,255));
       pMesas.setBackground(new java.awt.Color(24,168,255));
       //mpMante.setBackground(new java.awt.Color(24,168,255));
       pArea.setBackground(new java.awt.Color(255,51,51));
       pCargo.setBackground(new java.awt.Color(24,168,255));
       pComprobante.setBackground(new java.awt.Color(24,168,255));
       try {
            if(nPanel != null){
                getContentPane().remove(nPanel);
                getContentPane().repaint();
            }
            nPanel = new AreaL();
            nPanel.setBounds(255,59, widthvar-255, heightvar-59);
        
            getContentPane().add(nPanel);
            this.validate();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pAreaMouseClicked

    private void pComprobanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pComprobanteMouseClicked
       pUsuario.setBackground(new java.awt.Color(24,168,255));
       //mpPedido.setBackground(new java.awt.Color(24,168,255));
       pTrabajador.setBackground(new java.awt.Color(24,168,255));
       //mpReporte.setBackground(new java.awt.Color(24,168,255));
       pMesas.setBackground(new java.awt.Color(24,168,255));
       //mpMante.setBackground(new java.awt.Color(24,168,255));
       pArea.setBackground(new java.awt.Color(24,168,255));
       pCargo.setBackground(new java.awt.Color(24,168,255));
       pComprobante.setBackground(new java.awt.Color(255,51,51));
       
    }//GEN-LAST:event_pComprobanteMouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
            if (usuario.getNid_perfil() == 1 || usuario.getNid_perfil() == 2){
            pMesas.setVisible(true);
            pComprobante.setVisible(true);
            pUsuario.setVisible(true);
            pTrabajador.setVisible(true);
            pArea.setVisible(true);
            pCliente.setVisible(true);
            pComprobante.setVisible(true);
            pCargo.setVisible(true);
            pCategoria.setVisible(true);
            pEmpresa.setVisible(true);
            pLocal.setVisible(true);
            pPlato.setVisible(true);
            pPlatoLocal.setVisible(true);
            pPiso.setVisible(true);
            pComprobante.setVisible(false);
            
            mpMante.setVisible(true);
            mpPedido.setVisible(true);
            mpReporte.setVisible(true);}
            mpPedido.setBackground(new java.awt.Color(24,168,255));
            mpReporte.setBackground(new java.awt.Color(24,168,255));
            mpMante.setBackground(new java.awt.Color(24,168,255));
            if(nPanel != null){
                getContentPane().remove(nPanel);
                getContentPane().repaint();
            }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void pPisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPisoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pPisoMouseClicked

    private void pEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpresaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpresaMouseClicked

    private void pClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pClienteMouseClicked

    private void pLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLocalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pLocalMouseClicked

    private void pPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPlatoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pPlatoMouseClicked

    private void pCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pCategoriaMouseClicked

    private void pPlatoLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPlatoLocalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pPlatoLocalMouseClicked
    public void ValidarSub(int id){
        int vis = 14;
        int size = 0;
           
            size = (heightvar - pTop.getHeight())/vis;    //Alto de cada panel
            
            //s están FALSE, aquí se elige los que serán visibles (debe ser de acuerdo a la variable VIS)
            pMesas.setVisible(true);
            pComprobante.setVisible(true);
            pUsuario.setVisible(true);
            pTrabajador.setVisible(true);
            pArea.setVisible(true);
            pCliente.setVisible(true);
            pComprobante.setVisible(true);
            pCargo.setVisible(true);
            pCategoria.setVisible(true);
            pEmpresa.setVisible(true);
            pLocal.setVisible(true);
            pPlato.setVisible(true);
            pPlatoLocal.setVisible(true);
            pPiso.setVisible(true);
            //Los mismos paneles que se ha hecho VISIBLE, se setea LAYOUT = NULL (Para posicionar)
            pTrabajador.setLayout(null);
            pUsuario.setLayout(null);
            pMesas.setLayout(null);
            pComprobante.setLayout(null);
            pArea.setLayout(null);
            pCliente.setLayout(null);
            pComprobante.setLayout(null);
            pCargo.setLayout(null);
            pCategoria.setLayout(null);
            pEmpresa.setLayout(null);
            pLocal.setLayout(null);
            pPlato.setLayout(null);
            pPlatoLocal.setLayout(null);
            pPiso.setLayout(null);
            //Primer panel .... Lo mismo en los demás paneles, lo que varía es la posicion Y ( 59 + size * numeropanel) (EASY by Anibal XD)
            pUsuario.setBounds(0, 59 ,255,size);
            jLabel9.setBounds(105, size/2 - 15, 95, 26);
            jLabel10.setBounds(17, size/2 - 30, 64, 64);
            
            pTrabajador.setBounds(0, (59 + size), 255,size);
            jLabel1.setBounds(105, size/2 - 20, 142, 26);
            jLabel2.setBounds(17, size/2 - 50, 64, 64);
            
            pMesas.setBounds(0, 59 + (size*2), 255, size);
            jLabel11.setBounds(105, size/2 - 20,68 ,26);
            jLabel12.setBounds(17, size/2 - 40,64 ,64);                        
            
            pArea.setBounds(0,59 + (size*3),255,size);
            jLabel18.setBounds(105, size/2 - 20,68 ,26);
            jLabel19.setBounds(17, size/2 - 40, 64, 64);            
            
            pCargo.setBounds(0,59 + (size*4),255,size);
            jLabel36.setBounds(105, size/2 - 20,68 ,26);
            jLabel17.setBounds(17, size/2 - 40, 64, 64);
            
            pComprobante.setBounds(0, 59 + (size*5), 255, size);
            jLabel32.setBounds(105, size/2 - 20,68 ,26);
            jLabel33.setBounds(17, size/2 -40,64 ,64);
            
            pCategoria.setBounds(0,59 + (size*6),255,size);
            jLabel29.setBounds(105, size/2 - 20,68 ,26);
            jLabel30.setBounds(17, size/2 - 40, 64, 64);
            
            pCliente.setBounds(0,59 + (size*7),255,size);
            jLabel26.setBounds(105, size/2 - 20,68 ,26);
            jLabel27.setBounds(17, size/2 - 40, 64, 64);
            
            pComprobante.setBounds(0,59 + (size*8),255,size);
            jLabel20.setBounds(105, size/2 - 20,68 ,26);
            jLabel21.setBounds(17, size/2 - 40, 64, 64);
            
            pEmpresa.setBounds(0,59 + (size*9),255,size);
            jLabel17.setBounds(105, size/2 - 20,68 ,26);
            jLabel18.setBounds(17, size/2 - 40, 64, 64);
            
            pLocal.setBounds(0,59 + (size*10),255,size);
            jLabel28.setBounds(105, size/2 - 20,68 ,26);
            jLabel29.setBounds(17, size/2 - 40, 64, 64);
            
            pPlato.setBounds(0,59 + (size*11),255,size);
            jLabel30.setBounds(105, size/2 - 20,68 ,26);
            jLabel31.setBounds(17, size/2 - 40, 64, 64);
            
            pPlatoLocal.setBounds(0,59 + (size*12),255,size);
            jLabel34.setBounds(105, size/2 - 20,68 ,26);
            jLabel35.setBounds(17, size/2 - 40, 64, 64);
            
            pPiso.setBounds(0,59 + (size*13),255,size);
            jLabel22.setBounds(105, size/2 - 20,68 ,26);
            jLabel23.setBounds(17, size/2 - 40, 64, 64);
                                    
    }
    public void Validar(int id){
        int vis = 3;
        int size = 0;
        
        if(id == 1){
            
            vis = 3; //Cantidad de paneles se va a mostrar
            size = (heightvar - pTop.getHeight())/vis;    //Alto de cada panel
            
            //Al cargar el frame todos están FALSE, aquí se elige los que serán visibles (debe ser de acuerdo a la variable VIS)
            //pMesas.setVisible(true);
            mpMante.setVisible(true);
            mpReporte.setVisible(true);
            //pUsuario.setVisible(true);
            //pTrabajador.setVisible(true);
            mpPedido.setVisible(true);
            //pCargo.setVisible(true);
            //pArea.setVisible(true);
            
            //Los mismos paneles que se ha hecho VISIBLE, se setea LAYOUT = NULL (Para posicionar)
            //pTrabajador.setLayout(null);
            mpPedido.setLayout(null);
            //pUsuario.setLayout(null);
            mpReporte.setLayout(null);
            //pMesas.setLayout(null);
            mpMante.setLayout(null);
            //pCargo.setLayout(null);
            //pArea.setLayout(null);
            
            //Primer panel .... Lo mismo en los demás paneles, lo que varía es la posicion Y ( 59 + size * numeropanel) (EASY by Anibal XD)
            /*
            pUsuario.setBounds(0, 59 ,255,size);
            jLabel9.setBounds(105, size/2 - 15, 95, 26);
            jLabel10.setBounds(17, size/2 - 30, 64, 64);
            
            pTrabajador.setBounds(0, 59 + size, 255,size);
            jLabel1.setBounds(105, size/2 - 20, 142, 26);
            jLabel2.setBounds(17, size/2 - 52, 64, 64);
            
            pMesas.setBounds(0, 59 + size*2, 255, size);
            jLabel11.setBounds(105, size/2 - 20,68 ,26);
            jLabel12.setBounds(17, size/2 - 40,64 ,64);
            */
            mpMante.setBounds(0, 59, 255, size);
            jLabel13.setBounds(90, size/2 - 15,160 ,26);
            jLabel14.setBounds(17, size/2 -40,64 ,64);
            /*
            pCargo.setBounds(0, 59 + size*4, 255, size);
            jLabel16.setBounds(105, size/2 - 20,68 ,26);
            jLabel17.setBounds(17, size/2 - 40,64 ,64);
            
            pArea.setBounds(0, 59 + size*5, 255, size);
            jLabel18.setBounds(105, size/2 - 20,68 ,26);
            jLabel19.setBounds(17, size/2 - 40,64 ,64);*/
            
            mpPedido.setBounds(0, 59 + size, 255, size);
            jLabel3.setBounds(105, size/2 - 15, 73, 26);
            jLabel4.setBounds(17, size/2 - 30, 64, 64);
            
            mpReporte.setBounds(0,59 + size*2,255,size);
            jLabel7.setBounds(105, size/2 - 15, 85, 26);
            jLabel8.setBounds(17, size/2 - 40, 64, 64);
            
        }else if(id==2){
            vis = 2;
            size = (heightvar - pTop.getHeight())/vis;    
            //pMesas.setVisible(true);
            mpMante.setVisible(true);
            //pUsuario.setVisible(true);
            //pTrabajador.setVisible(true);
            mpPedido.setVisible(true);
            //pCargo.setVisible(true);
            //pArea.setVisible(true);
            //pTrabajador.setLayout(null);
            mpPedido.setLayout(null);
            //pUsuario.setLayout(null);
            //pMesas.setLayout(null);
            mpMante.setLayout(null);
            //pCargo.setLayout(null);
            //pArea.setLayout(null);
            
            /*pUsuario.setBounds(0, 59 ,255,size);
            jLabel9.setBounds(105, size/2 - 15, 95, 26);
            jLabel10.setBounds(17, size/2 - 30, 64, 64);
            
            pTrabajador.setBounds(0, 59 + size, 255,size);
            jLabel1.setBounds(105, size/2 - 20, 142, 26);
            jLabel2.setBounds(17, size/2 - 50, 64, 64);
            
            pMesas.setBounds(0, 59 + size*2, 255, size);
            jLabel11.setBounds(105, size/2 - 20,68 ,26);
            jLabel12.setBounds(17, size/2 - 40,64 ,64);*/
            
            mpMante.setBounds(0, 59, 255, size);
            jLabel13.setBounds(90, size/2 - 15,160 ,26);
            jLabel14.setBounds(17, size/2 -40,64 ,64);
            /*
            pCargo.setBounds(0, 59 + size*4, 255, size);
            jLabel16.setBounds(105, size/2 - 20,68 ,26);
            jLabel17.setBounds(17, size/2 - 40,64 ,64);
            
            pArea.setBounds(0, 59 + size*5, 255, size);
            jLabel18.setBounds(105, size/2 - 20,68 ,26);
            jLabel19.setBounds(17, size/2 - 40,64 ,64);
            */
            mpPedido.setBounds(0, 59 + size, 255, size);
            jLabel3.setBounds(105, size/2 - 15, 73, 26);
            jLabel4.setBounds(17, size/2 - 30, 64, 64);
        }else{
            vis = 1;
            size = (heightvar - pTop.getHeight())/vis;
            
            //pMesas.setVisible(true);
            mpPedido.setVisible(true);
            mpPedido.setLayout(null);
            //pMesas.setLayout(null);
        
            //pMesas.setBounds(0, 59, 255, size);
            //jLabel11.setBounds(105, size/2 - 20,68 ,26);
            //jLabel12.setBounds(17, size/2 - 40,64 ,64);
            
            mpPedido.setBounds(0, 59, 255, size);
            jLabel3.setBounds(105, size/2 - 15, 73, 26);
            jLabel4.setBounds(17, size/2 - 30, 64, 64);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel mpMante;
    private javax.swing.JPanel mpPedido;
    private javax.swing.JPanel mpReporte;
    private javax.swing.JPanel pArea;
    private javax.swing.JPanel pCargo;
    private javax.swing.JPanel pCategoria;
    private javax.swing.JPanel pCliente;
    private javax.swing.JPanel pComprobante;
    private javax.swing.JPanel pEmpresa;
    private javax.swing.JPanel pLocal;
    private javax.swing.JPanel pMesas;
    private javax.swing.JPanel pPiso;
    private javax.swing.JPanel pPlato;
    private javax.swing.JPanel pPlatoLocal;
    private javax.swing.JPanel pTop;
    private javax.swing.JPanel pTrabajador;
    private javax.swing.JPanel pUsuario;
    // End of variables declaration//GEN-END:variables
}
