/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas.presentacion.Area;

import java.sql.Date;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import ventas.modelo.Area;
import ventas.persistencia.util.BD_RS;
import ventas.persistencia.util.Method;

/**
 *
 * @author AnibalMA
 */
public class AreaL extends javax.swing.JPanel {
        public boolean Ed = false;
        public int idTbl;
    /**
     * Creates new form CargoL
     */
    public AreaL() {
        initComponents();
        cboEstado.setModel(BD_RS.ListarCBOEstado());
        
        cboEstado.setSelectedIndex(0);
        cboEstado.setVisible(false);
        lblEstado.setVisible(false);
        jPanel1.setVisible(false);
        jLabel19.setVisible(true);
        btnSearch.setVisible(true);
        txtFilter.setVisible(true);
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAreas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtName_Area = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        txtFilter = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/new.png"))); // NOI18N
        btnSave.setText("NUEVO");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 49, 180, 80));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel16.setText("GESTIÓN - ÁREAS");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 19, -1, 38));

        btnEditar.setBackground(new java.awt.Color(153, 153, 255));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/edit_user.png"))); // NOI18N
        btnEditar.setText("   EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 166, 180, 80));

        btnEliminar.setBackground(new java.awt.Color(153, 153, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/delete.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 279, 180, 80));

        tblAreas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAreas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 401, 1189, 373));

        txtName_Area.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel17.setText("NOMBRE:");

        lblEstado.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblEstado.setText("ESTADO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(26, 26, 26)
                    .addComponent(txtName_Area, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(115, 115, 115)
                    .addComponent(lblEstado)
                    .addGap(26, 26, 26)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(txtName_Area, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        txtFilter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFilter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFilter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFilterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFilterFocusLost(evt);
            }
        });
        add(txtFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 246, 322, 60));

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel19.setText("Búsqueda:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 191, -1, 29));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/search_2.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 62, 50));
    }// </editor-fold>//GEN-END:initComponents
    private void LoadTable(){
        tblAreas.setModel(BD_RS.ListarAreas());
        ConfigTbl();
    
    }
    private void ConfigTbl(){
        tblAreas.setDefaultEditor(Object.class, null);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int i = 0; i < tblAreas.getColumnCount(); i++){
            tblAreas.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            
        }
        for(int i = 0; i < tblAreas.getRowCount(); i++)
            tblAreas.setRowHeight(i, 45);
    }
    private boolean EC(){
        if(BD_RS.ExistArea(txtName_Area.getText())){
               JOptionPane.showMessageDialog(this, "Ya existe el Área " + txtName_Area.getText() ,"Mensaje",JOptionPane.INFORMATION_MESSAGE);
               txtName_Area.setText("");
               txtName_Area.requestFocus();
               return true; 
            }
         return false;
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       if(btnSave.getText().equals("NUEVO")){
           jLabel19.setVisible(false);
        btnSearch.setVisible(false);
        txtFilter.setVisible(false);
           jPanel1.setVisible(true);
           btnSave.setText("GUARDAR");
           btnSave.setIcon(new ImageIcon(getClass().getResource("/recursos/save.png")));
       }else{
            int t = 1;
           String msg = "";
            if(txtName_Area.getText().trim().length() != 0 && cboEstado.getSelectedIndex() != -1){
                //
                if (!Method.Caracter(txtName_Area.getText())){
                    JOptionPane.showMessageDialog(null, "Carácteres no permitidos");
                    txtName_Area.requestFocus();
                    return;
                }
                Area area = new Area();
                if(area.getNombre() == null || !Ed){
                     if (EC()) return;
               }else if(Ed){
                    if(!area.getNombre().equals(txtName_Area.getText())){
                     if (EC()) return;
                    }
               }

                if(!Ed){
                 t = 1;   
                 msg = "Área Guardada";
                area.setId(BD_RS.CodArea());
                area.setEstado(1);
                area.setFe_creacion(Date.valueOf(LocalDate.now()));
                area.setNombre(txtName_Area.getText());
                }else{
                    t = 2;
                    msg = "Área Actualizada";
                   area.setId(idTbl);
                   area.setEstado(cboEstado.getSelectedIndex()+1);
                   area.setFe_mod(Date.valueOf(LocalDate.now()));
                   area.setNombre(txtName_Area.getText());
                }

                if(BD_RS.CArea(area, t)) {
                        JOptionPane.showMessageDialog(this, msg,"Mensaje",JOptionPane.INFORMATION_MESSAGE);
                        tblAreas.setModel(BD_RS.ListarAreas());
                        LoadTable();
                        lblEstado.setVisible(false);
                        cboEstado.setVisible(false);
                        t = 1;
                        Ed = false;
                        txtName_Area.setText("");
                        txtName_Area.requestFocus();
                        jPanel1.setVisible(false);
                        btnSave.setText("NUEVO");
                        btnSave.setIcon(new ImageIcon(getClass().getResource("/recursos/new.png")));
                        jLabel19.setVisible(true);
                        btnSearch.setVisible(true);
                        txtFilter.setVisible(true);
                    }
                    else JOptionPane.showMessageDialog(this, "Se ha producido un error al guardar el Área","Mensaje",JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Complete todos los campos para continuar","Mensaje",JOptionPane.WARNING_MESSAGE);
            }
       }
    }//GEN-LAST:event_btnSaveActionPerformed
    private void Mod(){
        int i = tblAreas.getSelectedRow();
        if(i >= 0){
            if(btnSave.getText().equals("NUEVO")){
                jLabel19.setVisible(false);
                btnSearch.setVisible(false);
                txtFilter.setVisible(false);
           jPanel1.setVisible(true);
           btnSave.setText("GUARDAR");
           btnSave.setIcon(new ImageIcon(getClass().getResource("/recursos/save.png")));  }
            Ed = true;
            Area area = new Area();
            area.setNombre(tblAreas.getValueAt(i, 1).toString());
            cboEstado.setVisible(true);
            lblEstado.setVisible(true);
            idTbl = Integer.parseInt(tblAreas.getValueAt(i, 0).toString());
            txtName_Area.setText(tblAreas.getValueAt(i, 1).toString());
            cboEstado.setSelectedIndex(BD_RS.GetIdEstado(tblAreas.getValueAt(i, 3).toString())-1);
       }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro a modificar","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void Del(){
         int i = tblAreas.getSelectedRow();
        if(i >= 0){
            if(tblAreas.getValueAt(i, 3).toString().contains("Inactivo")){
                 JOptionPane.showMessageDialog(null, "El Área ya se encuentra deshabilitado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
             }else{
                 int r = JOptionPane.showOptionDialog(null,"¿Está seguro de deshabilitar el Área " + tblAreas.getValueAt(i, 1).toString() + " ?","Mensaje",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,null,null);
                 if(r == 0){
                                Ed = false;
                                cboEstado.setVisible(false);
                                lblEstado.setVisible(false);
                                txtName_Area.setText("");

                                Area area = new Area();
                                area.setId(Integer.parseInt(tblAreas.getValueAt(i, 0).toString()));
                                area.setEstado(2);
                       if(BD_RS.CArea(area, 3)) {
                           JOptionPane.showMessageDialog(null, "Registro Deshabilitado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                           LoadTable();
                       }else{
                           JOptionPane.showMessageDialog(null, "Ocurrio un error al deshabilitar el Área","Mensaje",JOptionPane.WARNING_MESSAGE);
                       }
                 }
            }
            
       }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro a modificar","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        Mod();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
            Del();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtFilterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFilterFocusGained

    }//GEN-LAST:event_txtFilterFocusGained

    private void txtFilterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFilterFocusLost

    }//GEN-LAST:event_txtFilterFocusLost

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(txtFilter.getText().length() != 0){
             tblAreas.setModel(BD_RS.CAreasFiltro(txtFilter.getText()));
             ConfigTbl();
        }else{
            LoadTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private static javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTable tblAreas;
    private javax.swing.JTextField txtFilter;
    private javax.swing.JTextField txtName_Area;
    // End of variables declaration//GEN-END:variables
}
